import './globals.css'
import Navbar  from '../components/Navbar';
import Footer from '@/components/Footer';
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar/>
        <div className="min-h-[84.2vh] bg-gray-100">
        {children}
        </div>
        <Footer/>
        
      </body>
      
    </html>
  )
}
