import './globals.css'
import Navbar from '../components/Navbar'
import SessionWrapper from '@/components/SessionWrapper'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <SessionWrapper>
          <Navbar />
          <div className=" overflow-y-scroll min-h-screen w-full fixed inset-0 -z-10 bg-[#000000] bg-[radial-gradient(#ffffff33_1px,#00091d_1px)] bg-[length:20px_20px]">
            {children}
          </div>

        </SessionWrapper>
      </body>
    </html>
  )
}
