import '../globals.css'
import SessionWrapper from '@/components/SessionWrapper'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <SessionWrapper>
          <div className="h-[100vh]bg-[#000000] bg-[radial-gradient(#ffffff33_1px,#00091d_1px)] bg-[size:20px_20px]" />
          <main className="flex-grow flex h-[100vh] flex-col items-center justify-center text-white">
            {children}
          </main>
          
        </SessionWrapper>

      </body>
    </html>
  )
}
